name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          node_image: kindest/node:v1.31.1 # renovate: packageName=kindest/node
          version: v0.24.0 # renovate: packageName=kubernetes-sigs/kind
          cluster_name: kind

      - name: Install
        run: make install
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
