name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:v1.29.2 # renovate: packageName=kindest/node
          version: v0.22.0 # renovate: packageName=kubernetes-sigs/kind
          cluster_name: kind

      - name: Install
        run: make install
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
