name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          node_image: kindest/node:v1.37.0 # renovate: packageName=kindest/node
          version: v0.33.0 # renovate: packageName=kubernetes-sigs/kind
          cluster_name: kind

      - name: Install
        run: make install
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
