name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          node_image: kindest/node:v1.36.1 # renovate: packageName=kindest/node
          version: v0.32.0 # renovate: packageName=kubernetes-sigs/kind
          cluster_name: kind

      - name: Install
        run: make install
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
